// 모든 비즈니스 영어 학습 데이터
const businessEnglishData = {
    'ask_questions_in_conferences': {
        name: '컨퍼런스에서 질문하기',
        sentences: [
            { korean: "오늘 일정은 무엇인가요?", english: "What's the schedule for today?" },
            { korean: "세션은 오전 9시에 시작됩니다.", english: "Sessions start at 9:00 a.m." },
            { korean: "유인물을 어디서 찾을 수 있나요?", english: "Where can we find handouts?" },
            { korean: "입구에서 제공됩니다.", english: "They're available at the entrance." },
            { korean: "그 점을 다시 말씀해 주시겠습니까?", english: "Could you repeat that point?" },
            { korean: "물론, 다시 설명드리겠습니다.", english: "Certainly, let me go over it." },
            { korean: "다음 연사는 누구인가요?", english: "Who's the next speaker?" },
            { korean: "스미스 박사가 다음으로 연설합니다.", english: "Dr. Smith will speak next." },
            { korean: "질문과 답변 세션이 있나요?", english: "Is there a Q&A session?" },
            { korean: "네, 강연 직후에 있습니다.", english: "Yes, right after the talk." },
            { korean: "발표 자료를 받을 수 있나요?", english: "Can we get the presentation slides?" },
            { korean: "웹사이트에서 다운로드할 수 있습니다.", english: "You can download them from the website." },
            { korean: "질문이 있습니다.", english: "I have a question." },
            { korean: "마이크를 사용해 주세요.", english: "Please use the microphone." },
            { korean: "이해하지 못한 부분이 있습니다.", english: "I didn't understand a part." },
            { korean: "다시 설명해 드리겠습니다.", english: "I'll explain it again." }
        ]
    },
    'business_travel': {
        name: '출장',
        sentences: [
            { korean: "비행기 출발 시간이 언제인가요?", english: "When's our flight departure?" },
            { korean: "비행기는 오후 5시에 출발합니다.", english: "The flight departs at 5:00 p.m." },
            { korean: "택시가 필요하시나요?", english: "Do you need a taxi?" },
            { korean: "네, 택시를 불러주세요.", english: "Yes, please call a taxi." },
            { korean: "호텔은 어디에 있나요?", english: "Where is the hotel located?" },
            { korean: "도심 근처에 있습니다.", english: "It's near the downtown area." },
            { korean: "예약이 있으신가요?", english: "Do you have a reservation?" },
            { korean: "네, 예약이 있습니다.", english: "Yes, I have a booking." },
            { korean: "공항까지 얼마나 멀리 있나요?", english: "How far is the airport?" },
            { korean: "30분 거리입니다.", english: "It's 30 minutes away." },
            { korean: "숙박을 확인해 줄 수 있나요?", english: "Can you confirm my stay?" },
            { korean: "숙박이 확인되었습니다.", english: "Your stay is confirmed." },
            { korean: "조식이 포함되어 있나요?", english: "Is breakfast included?" },
            { korean: "네, 조식이 포함되어 있습니다.", english: "Yes, breakfast is included." },
            { korean: "회의는 언제인가요?", english: "When is the meeting?" },
            { korean: "회의는 오전 10시에 있습니다.", english: "The meeting is at 10:00 a.m." },
            { korean: "지도 있으신가요?", english: "Do you have a map?" },
            { korean: "네, 여기 지도 있습니다.", english: "Yes, here is a map." },
            { korean: "가장 가까운 식당은 어디인가요?", english: "Where's the nearest restaurant?" },
            { korean: "근처에 하나 있습니다.", english: "There's one nearby." },
            { korean: "여기서 와이파이를 사용할 수 있나요?", english: "Can I get Wi-Fi here?" },
            { korean: "네, 와이파이가 제공됩니다.", english: "Yes, Wi-Fi is available." },
            { korean: "체크아웃 시간은 언제인가요?", english: "What's the checkout time?" },
            { korean: "체크아웃은 정오입니다.", english: "Checkout is at noon." },
            { korean: "룸서비스가 있나요?", english: "Is there room service?" },
            { korean: "네, 룸서비스가 제공됩니다.", english: "Yes, room service is available." },
            { korean: "회의실은 어디에 있나요?", english: "Where is the conference room?" },
            { korean: "2층에 있습니다.", english: "It's on the second floor." },
            { korean: "송장을 받을 수 있나요?", english: "Can I get an invoice?" },
            { korean: "네, 여기 송장 있습니다.", english: "Yes, here's your invoice." },
            { korean: "이 자리가 사용 중인가요?", english: "Is this seat taken?" },
            { korean: "아니요, 여기 앉으셔도 됩니다.", english: "No, you can sit here." },
            { korean: "거스름돈 있으신가요?", english: "Do you have change?" },
            { korean: "네, 거스름돈 있습니다.", english: "Yes, I have change." },
            { korean: "길 안내를 받을 수 있나요?", english: "Can I get directions?" },
            { korean: "네, 어디로 가시고 싶으신가요?", english: "Yes, where do you need directions?" },
            { korean: "환율이 얼마인가요?", english: "What's the exchange rate?" },
            { korean: "유로당 1.2달러입니다.", english: "It's $1.2 per Euro." },
            { korean: "여기에 체육관이 있나요?", english: "Is there a gym here?" },
            { korean: "네, 체육관이 열려 있습니다.", english: "Yes, the gym is open." },
            { korean: "셔틀 서비스를 제공하나요?", english: "Do you offer shuttle service?" },
            { korean: "네, 셔틀 서비스가 제공됩니다.", english: "Yes, shuttle service is offered." }
        ]
    },
    'conference_ice_breakers': {
        name: '컨퍼런스 아이스브레이커',
        sentences: [
            { korean: "이름이 어떻게 되시나요?", english: "What's your name?" },
            { korean: "저는 존 도입니다.", english: "I am John Doe." },
            { korean: "자주 오시나요?", english: "Come here often?" },
            { korean: "사실 처음입니다.", english: "First time, actually." },
            { korean: "컨퍼런스 즐기고 계신가요?", english: "Enjoying the conference?" },
            { korean: "네, 매우 유익합니다.", english: "Yes, quite informative." },
            { korean: "어디서 오셨나요?", english: "Where are you from?" },
            { korean: "뉴욕에서 왔습니다.", english: "From New York." },
            { korean: "어떤 분야에서 일하시나요?", english: "What's your field?" },
            { korean: "IT 분야에서 일합니다.", english: "I work in IT." },
            { korean: "좋은 강연을 보셨나요?", english: "Seen any good talks?" },
            { korean: "몇 개 흥미로운 강연이 있었습니다.", english: "A few interesting ones." },
            { korean: "좋아하는 연사는 있나요?", english: "Got a favorite speaker?" },
            { korean: "아직 결정하지 못했습니다.", english: "Still deciding on that." },
            { korean: "나중에 뷔페를 시도할 건가요?", english: "Trying the buffet later?" },
            { korean: "아마도, 좋다고 들었습니다.", english: "Maybe, heard it's good." },
            { korean: "워크숍에 참여했나요?", english: "Attend any workshops?" },
            { korean: "네, 어제 두 개 참석했습니다.", english: "Yes, two yesterday." },
            { korean: "여기 왜 오셨나요?", english: "What brings you here?" },
            { korean: "주로 네트워킹을 위해 왔습니다.", english: "Here to network, mostly." },
            { korean: "흥미로운 사람을 만났나요?", english: "Meet anyone interesting?" },
            { korean: "몇몇 연결을 만들었습니다.", english: "A few, making connections." },
            { korean: "얼마나 오래 머무르시나요?", english: "How long are you staying?" },
            { korean: "오늘 밤 떠나야 해서 아쉽습니다.", english: "Leaving tonight, sadly." },
            { korean: "무료 기념품을 챙기셨나요?", english: "Grabbed any freebies?" },
            { korean: "멋진 핀을 몇 개 얻었습니다.", english: "Got some nice pins." },
            { korean: "명함을 교환할까요?", english: "Exchange business cards?" },
            { korean: "물론, 여기 제 명함입니다.", english: "Sure, here's mine." },
            { korean: "도시를 즐기고 계신가요?", english: "Enjoying the city?" },
            { korean: "네, 여기가 아름답습니다.", english: "Yes, it's beautiful here." },
            { korean: "갈라 디너에 참석할 건가요?", english: "Attend the gala dinner?" },
            { korean: "네, 참석할 계획입니다.", english: "Planning to, yes." },
            { korean: "첫 컨퍼런스인가요?", english: "Your first conference?" },
            { korean: "아니요, 여러 번 참석했습니다.", english: "No, been to many." }
        ]
    },
    'conferences': {
        name: '컨퍼런스',
        sentences: [
            { korean: "제 목소리가 들리나요?", english: "Can you hear me?" },
            { korean: "네, 잘 들립니다.", english: "Yes, I can hear you." },
            { korean: "일정은 어디서 확인하나요?", english: "Where's the schedule?" },
            { korean: "컨퍼런스 앱에서 확인할 수 있습니다.", english: "It's on the conference app." },
            { korean: "다음 연사는 누구인가요?", english: "Who's the next speaker?" },
            { korean: "스미스 박사가 다음으로 연설합니다.", english: "Dr. Smith will speak next." },
            { korean: "곧 휴식 시간이 있나요?", english: "Is there a break soon?" },
            { korean: "네, 10분 후입니다.", english: "Yes, in 10 minutes." },
            { korean: "질문해도 될까요?", english: "Can I ask a question?" },
            { korean: "질문을 진행해 주세요.", english: "Please go ahead and ask." },
            { korean: "화장실은 어디인가요?", english: "Where's the restroom, please?" },
            { korean: "복도를 따라 왼쪽에 있습니다.", english: "Down the hall to the left." },
            { korean: "여기서 와이파이를 사용할 수 있나요?", english: "Is there Wi-Fi here?" },
            { korean: "비밀번호는 게시판에 있습니다.", english: "Yes, the password is on the board." },
            { korean: "행사가 언제 끝나나요?", english: "What time does it end?" },
            { korean: "오후 5시에 끝납니다.", english: "It finishes at 5:00 p.m." },
            { korean: "물을 좀 마실 수 있을까요?", english: "May I get some water?" },
            { korean: "물은 밖에 준비되어 있습니다.", english: "Water is available outside." },
            { korean: "사진을 찍어도 되나요?", english: "Can we take a photo?" },
            { korean: "물론, 지금 찍읍시다.", english: "Of course, let's take it now." },
            { korean: "명함 있으신가요?", english: "Do you have a card?" },
            { korean: "네, 여기 제 명함입니다.", english: "Yes, here is my business card." },
            { korean: "다시 말씀해 주시겠습니까?", english: "Can you repeat that, please?" },
            { korean: "물론, 다시 말씀드리겠습니다.", english: "Sure, I'll say it again." },
            { korean: "이 자리가 사용 중인가요?", english: "Is this seat taken?" },
            { korean: "아니요, 여기 앉으셔도 됩니다.", english: "No, you can sit here." },
            { korean: "추천하는 세션이 있나요?", english: "What sessions are recommended?" },
            { korean: "프로그램 가이드를 확인하세요.", english: "Check the program guide." },
            { korean: "점심이 포함되어 있나요?", english: "Is lunch included?" },
            { korean: "네, 메인 홀에서 제공됩니다.", english: "Yes, it's in the main hall." },
            { korean: "로그인은 어떻게 하나요?", english: "How do I log in?" },
            { korean: "등록한 이메일을 사용하세요.", english: "Use the email you registered with." },
            { korean: "철자를 알려주시겠습니까?", english: "Could you spell that?" },
            { korean: "물론, S-M-I-T-H입니다.", english: "Sure, S-M-I-T-H." }
        ]
    },
    'external_meetings': {
        name: '외부 회의',
        sentences: [
            { korean: "지금 시작할 수 있나요?", english: "Can we start now?" },
            { korean: "네, 회의를 시작합시다.", english: "Yes, let's begin the meeting." },
            { korean: "보고서 있으신가요?", english: "Do you have the report?" },
            { korean: "네, 여기 있습니다.", english: "Yes, it's right here." },
            { korean: "좀 더 크게 말씀해 주시겠습니까?", english: "Could you speak louder?" },
            { korean: "이제 나아졌나요?", english: "Sure, is this better?" },
            { korean: "오늘 의제는 무엇인가요?", english: "What is the agenda today?" },
            { korean: "프로젝트 업데이트를 논의할 것입니다.", english: "We will discuss project updates." },
            { korean: "프로젝트에 대한 업데이트 있나요?", english: "Any updates on the project?" },
            { korean: "네, 잘 진행되고 있습니다.", english: "Yes, it's progressing well." },
            { korean: "우려 사항이 있나요?", english: "Do you have any concerns?" },
            { korean: "아니요, 모든 것이 괜찮아 보입니다.", english: "No, everything seems fine." },
            { korean: "회의를 재조정할 수 있나요?", english: "Can we reschedule the meeting?" },
            { korean: "내일 아침은 어떠신가요?", english: "Yes, how about tomorrow morning?" },
            { korean: "그 점을 명확히 설명해 주시겠습니까?", english: "Could you clarify that point?" },
            { korean: "물론, 다시 설명드리겠습니다.", english: "Sure, let me explain it again." },
            { korean: "지금까지 질문 있나요?", english: "Any questions so far?" },
            { korean: "모든 것이 명확합니다.", english: "No, everything is clear." },
            { korean: "마지막 부분을 다시 말씀해 주시겠습니까?", english: "Could you repeat the last part?" },
            { korean: "물론, 다시 말씀드리겠습니다.", english: "Of course, let me repeat it." },
            { korean: "프로젝트가 어떻게 진행되고 있나요?", english: "How is the project going?" },
            { korean: "계획대로 진행되고 있습니다.", english: "It is going as planned." },
            { korean: "다음 단계는 무엇인가요?", english: "What are the next steps?" },
            { korean: "디자인을 최종 확정해야 합니다.", english: "We need to finalize the design." },
            { korean: "마감일은 언제인가요?", english: "When is the deadline?" },
            { korean: "마감일은 다음 금요일입니다.", english: "The deadline is next Friday." },
            { korean: "다른 의견 있나요?", english: "Any other comments?" },
            { korean: "아니요, 그게 전부인 것 같습니다.", english: "No, I think that's all." },
            { korean: "사본을 받을 수 있나요?", english: "Can I get a copy?" },
            { korean: "네, 이메일로 보내드리겠습니다.", english: "Yes, I'll email it to you." },
            { korean: "다른 회의가 있나요?", english: "Will there be another meeting?" },
            { korean: "네, 다음 회의는 다음 달입니다.", english: "Yes, next meeting is next month." },
            { korean: "더 일찍 만날 수 있나요?", english: "Can we meet earlier?" },
            { korean: "어떤 시간이 맞으신가요?", english: "Sure, what time suits you?" },
            { korean: "판매 실적은 어떠한가요?", english: "How are the sales figures?" },
            { korean: "실적이 꾸준히 향상되고 있습니다.", english: "The figures are improving steadily." },
            { korean: "진행할 수 있나요?", english: "Can we proceed?" },
            { korean: "네, 계속 진행해 주세요.", english: "Yes, go ahead please." }
        ]
    },
    'internal_mail': {
        name: '내부 메일',
        sentences: [
            { korean: "업데이트해 주셔서 감사합니다.", english: "Thank you for your update." },
            { korean: "완전한 파일을 보내주세요.", english: "Please send the complete file." },
            { korean: "회의를 예약할 수 있나요?", english: "Can we schedule a meeting?" },
            { korean: "당신의 피드백이 필요합니다.", english: "I need your feedback." },
            { korean: "계속 업데이트드리겠습니다.", english: "We'll keep you updated." },
            { korean: "회신을 기대하겠습니다.", english: "Looking forward to your reply." },
            { korean: "첨부된 문서를 확인해 주세요.", english: "Please find the attached document." },
            { korean: "이것에 대해 더 논의합시다.", english: "Let's discuss this further." },
            { korean: "승인을 받을 수 있나요?", english: "Can I get your approval?" },
            { korean: "의견을 공유해 주세요.", english: "Share your thoughts, please." },
            { korean: "이 마감일이 실현 가능한가요?", english: "Is this deadline achievable?" },
            { korean: "도움 주셔서 감사합니다.", english: "Thanks for your assistance." },
            { korean: "세부사항을 확인해 줄 수 있나요?", english: "Can you confirm the details?" },
            { korean: "업데이트된 정보를 확인하세요.", english: "Check the updated information." },
            { korean: "제안서를 검토해 주세요.", english: "Kindly review the proposal." },
            { korean: "추가 정보를 제공해 줄 수 있나요?", english: "Could you provide more information?" },
            { korean: "불일치를 명확히 해주세요.", english: "Please clarify the discrepancies." },
            { korean: "적합한지 알려주세요.", english: "Let me know if suitable." },
            { korean: "프로젝트 계획이 첨부되어 있습니다.", english: "The project plan is attached." },
            { korean: "회의록을 공유해 주세요.", english: "Share the meeting notes, please." },
            { korean: "곧 업데이트드리겠습니다.", english: "I will update you soon." },
            { korean: "당신의 의견이 소중합니다.", english: "Your input is valuable." },
            { korean: "이 업무를 우선순위에 두세요.", english: "Please prioritize this task." },
            { korean: "예산이 승인되었나요?", english: "Is the budget approved?" },
            { korean: "보고서를 최종 확정합시다.", english: "Let's finalize the report." },
            { korean: "가능한 시간을 보내주세요.", english: "Send your availability, please." },
            { korean: "제시간에 배달을 보장해 주세요.", english: "Please ensure timely delivery." },
            { korean: "파일에 대한 업데이트 있나요?", english: "Any updates on the file?" },
            { korean: "피드백에 감사드립니다.", english: "Your feedback is appreciated." },
            { korean: "수정된 버전이 첨부되어 있습니다.", english: "Attached is the revised version." },
            { korean: "추가 세부사항이 필요합니다.", english: "I need further details." },
            { korean: "다음 단계는 무엇인가요?", english: "What are the next steps?" },
            { korean: "빠른 응답에 감사드립니다.", english: "Thanks for your prompt response." },
            { korean: "곧 팀 회의를 예약합시다.", english: "Schedule a team meeting soon." },
            { korean: "마감일을 연장할 수 있나요?", english: "Can we extend the deadline?" },
            { korean: "보고서가 첨부되어 있습니다.", english: "Please find the report attached." }
        ]
    },
    'internal_meetings': {
        name: '내부 회의',
        sentences: [
            { korean: "오늘 의제는 무엇인가요?", english: "What is our agenda?" },
            { korean: "분기별 결과를 논의할 예정입니다.", english: "Discussing the quarterly results." },
            { korean: "프로젝트에 대한 업데이트 있나요?", english: "Any updates on the project?" },
            { korean: "네, 일정보다 앞서 완료되었습니다.", english: "Yes, completed ahead of schedule." },
            { korean: "모두 보고서를 검토했나요?", english: "Did everyone review the reports?" },
            { korean: "아직 검토하지 못해 죄송합니다.", english: "I haven't, apologies." },
            { korean: "주요 문제는 무엇인가요?", english: "What are the major issues?" },
            { korean: "예산 제약과 지연입니다.", english: "Budget constraints and delays." },
            { korean: "새로운 이니셔티브를 누가 이끌나요?", english: "Who leads the new initiative?" },
            { korean: "로라가 맡을 것입니다.", english: "Laura will handle it." },
            { korean: "재정부터 시작할까요?", english: "Shall we begin with finances?" },
            { korean: "네, 예산을 검토합시다.", english: "Yes, let's review the budget." },
            { korean: "마감일을 설정할 수 있나요?", english: "Can we set a deadline?" },
            { korean: "다음 달 말입니다.", english: "End of next month." },
            { korean: "현재 전략에 대한 우려 사항이 있나요?", english: "Any concerns with current strategies?" },
            { korean: "마케팅 노력을 더 늘려야 합니다.", english: "Need more marketing efforts." },
            { korean: "어떻게 진행해야 하나요?", english: "How should we proceed?" },
            { korean: "파일럿 테스트부터 시작합시다.", english: "Start with a pilot test." },
            { korean: "클라이언트 피드백이 긍정적이었나요?", english: "Was the client feedback positive?" },
            { korean: "대체로 좋았으나 사소한 문제가 있었습니다.", english: "Mostly good, few minor issues." },
            { korean: "어떤 위험이 있나요?", english: "What are the risks involved?" },
            { korean: "납품 지연 가능성이 있습니다.", english: "Potential delays in delivery." },
            { korean: "이해관계자들에게 정보가 전달되었나요?", english: "Are the stakeholders informed?" },
            { korean: "오늘 업데이트될 것입니다.", english: "They will be updated today." },
            { korean: "다음 회의는 언제인가요?", english: "When is the next meeting?" },
            { korean: "다음 주 같은 시간입니다.", english: "Same time next week." },
            { korean: "마지막 의견 있나요?", english: "Any final thoughts?" },
            { korean: "제 입장에서는 모두 괜찮습니다.", english: "All good on my end." },
            { korean: "회의를 종료할까요?", english: "Shall we adjourn?" },
            { korean: "네, 회의가 종료되었습니다.", english: "Yes, meeting concluded." },
            { korean: "회의록은 누가 작성하나요?", english: "Who takes the minutes?" },
            { korean: "이번에는 마이크가 자원했습니다.", english: "Mike volunteered this time." },
            { korean: "액션 플랜이 명확한가요?", english: "Is the action plan clear?" },
            { korean: "완전히 명확하며 모두가 자신의 업무를 알고 있습니다.", english: "Absolutely, everyone knows their tasks." }
        ]
    },
    'internal_supplies': {
        name: '내부 용품',
        sentences: [
            { korean: "펜이 필요합니다.", english: "Need a pen, please." },
            { korean: "여기 제 펜 사용하세요.", english: "Here, use mine." },
            { korean: "스테이플러는 어디 있나요?", english: "Where's the stapler?" },
            { korean: "책상 모서리에 있습니다.", english: "On the desk corner." },
            { korean: "가위를 빌릴 수 있나요?", english: "May I borrow scissors?" },
            { korean: "네, 나중에 반납해 주세요.", english: "Yes, return them later." },
            { korean: "종이를 가져갈 수 있나요?", english: "Can I take paper?" },
            { korean: "선반에서 가져가세요.", english: "Take from the shelf." },
            { korean: "테이프는 누가 가지고 있나요?", english: "Who has the tape?" },
            { korean: "여기 있습니다.", english: "I have it here." },
            { korean: "마커가 있나요?", english: "Are markers available?" },
            { korean: "첫 번째 서랍을 확인해 보세요.", english: "Check the first drawer." },
            { korean: "프린터가 비어 있나요?", english: "Is the printer free?" },
            { korean: "지금 비어 있습니다.", english: "It's free now." },
            { korean: "복사에 도움이 필요합니다.", english: "Need help photocopying." },
            { korean: "방법을 보여드리겠습니다.", english: "Please show me how." },
            { korean: "봉투가 남아 있나요?", english: "Any envelopes left?" },
            { korean: "캐비닛에 몇 개 있습니다.", english: "Some are in the cabinet." },
            { korean: "형광펜을 사용할 수 있나요?", english: "Can I use the highlighter?" },
            { korean: "네, 하지만 아껴서 사용하세요.", english: "Yes, but use sparingly." },
            { korean: "누가 제 계산기를 가져갔나요?", english: "Who took my calculator?" },
            { korean: "제가 가지고 있어요, 죄송합니다.", english: "It's with me, sorry." },
            { korean: "스티커 메모지가 더 필요합니다.", english: "Need more sticky notes." },
            { korean: "비품실에서 가져가세요.", english: "Grab from the supply room." },
            { korean: "여분의 잉크가 있나요?", english: "Is there extra ink?" },
            { korean: "상단 선반에 있습니다.", english: "Yes, on the top shelf." },
            { korean: "스테이플을 어떻게 채우나요?", english: "How to refill staples?" },
            { korean: "도와드리겠습니다.", english: "I'll help you with that." },
            { korean: "서류 캐비닛이 잠겨 있나요?", english: "Filing cabinets locked?" },
            { korean: "낸시가 열쇠를 가지고 있습니다.", english: "The keys are with Nancy." },
            { korean: "종이 클립이 있나요?", english: "Do we have paper clips?" },
            { korean: "파란 상자에 있습니다.", english: "In the blue box." },
            { korean: "프린터 용지가 필요합니다.", english: "Printer paper needed." },
            { korean: "창고에서 채워 넣으세요.", english: "Refill from the store room." }
        ]
    },
    'introducing_company': {
        name: '회사 소개',
        sentences: [
            { korean: "안녕하세요, 저희는 ABC LTD입니다.", english: "Hello, we are ABC LTD." },
            { korean: "귀사는 어떤 일을 하나요?", english: "What does your company do?" },
            { korean: "우리는 웹 솔루션을 제공합니다.", english: "We provide web solutions." },
            { korean: "귀사는 어디에 위치해 있나요?", english: "Where is your company located?" },
            { korean: "본사는 뉴욕에 있습니다.", english: "Our headquarters is in New York." },
            { korean: "ABC는 언제 설립되었나요?", english: "How long has ABC existed?" },
            { korean: "2005년에 시작했습니다.", english: "We started in 2005." },
            { korean: "핵심 가치는 무엇인가요?", english: "What are your core values?" },
            { korean: "혁신, 성실, 커뮤니티입니다.", english: "Innovation, integrity, and community." },
            { korean: "글로벌 사무소가 있나요?", english: "Do you have global offices?" },
            { korean: "네, 여러 나라에 있습니다.", english: "Yes, in several countries." },
            { korean: "주요 고객은 누구인가요?", english: "Who are your main clients?" },
            { korean: "주로 테크 기업들을 대상으로 합니다.", english: "We serve mainly tech companies." },
            { korean: "회사에 대한 추가 정보를 보내줄 수 있나요?", english: "Can you send more company details?" },
            { korean: "네, 프로필을 이메일로 보내겠습니다.", english: "Yes, I'll email our profile." },
            { korean: "현재 채용 중인가요?", english: "Are you hiring currently?" },
            { korean: "네, 주로 개발 직원을 채용 중입니다.", english: "Yes, primarily in development." },
            { korean: "무역 박람회에 참석하나요?", english: "Do you attend trade shows?" },
            { korean: "네, 주요 행사에 매년 참석합니다.", english: "Yes, annually at major events." },
            { korean: "고객 지원 서비스가 있나요?", english: "Do you have customer support?" },
            { korean: "24시간 전화 및 온라인 지원이 있습니다.", english: "24/7 phone and online support." },
            { korean: "귀사를 차별화하는 점은 무엇인가요?", english: "What sets your company apart?" },
            { korean: "맞춤화와 고객 서비스입니다.", english: "Our customization and client service." },
            { korean: "다른 회사와 파트너십을 맺나요?", english: "Do you partner with others?" },
            { korean: "네, 선도적인 소프트웨어 회사들과 협력합니다.", english: "Yes, with leading software companies." },
            { korean: "귀사는 친환경적인가요?", english: "Is your company eco-friendly?" },
            { korean: "우리는 친환경 프로토콜을 따릅니다.", english: "We follow green protocols." },
            { korean: "주식 시장에 상장되어 있나요?", english: "Are you listed on any street?" },
            { korean: "네, 뉴욕 증권 거래소에 상장되어 있습니다.", english: "Yes, on the New York Stock Exchange." },
            { korean: "최근 회사 성과는 무엇인가요?", english: "Any recent company achievements?" },
            { korean: "작년에 최고 스타트업 상을 수상했습니다.", english: "Awarded best startup last year." },
            { korean: "리뷰는 어디서 읽을 수 있나요?", english: "Where can I read reviews?" },
            { korean: "웹사이트의 고객 후기 섹션을 확인하세요.", english: "Check our website's testimonial section." }
        ]
    },
    'job_interviews': {
        name: '면접',
        sentences: [
            { korean: "자신에 대해 말씀해 주세요.", english: "Tell me about yourself." },
            { korean: "저는 성실하고 시간 엄수를 잘합니다.", english: "I am dedicated and punctual." },
            { korean: "당신의 강점은 무엇인가요?", english: "What is your strength?" },
            { korean: "저는 조직화에 능숙합니다.", english: "I'm good at organizing." },
            { korean: "압박을 잘 다룰 수 있나요?", english: "Can you handle pressure?" },
            { korean: "네, 저는 스트레스를 잘 관리합니다.", english: "Yes, I manage stress well." },
            { korean: "당신의 약점은 무엇인가요?", english: "What are your weaknesses?" },
            { korean: "저는 영어를 개선하고 있습니다.", english: "I am improving my English." },
            { korean: "왜 우리가 당신을 고용해야 하나요?", english: "Why should we hire you?" },
            { korean: "저는 매우 헌신적입니다.", english: "I am very committed." },
            { korean: "당신이 직면했던 도전을 설명해 주세요.", english: "Describe a challenge you faced." },
            { korean: "저는 매출 부진을 극복했습니다.", english: "I overcame a sales slump." },
            { korean: "성공을 어떻게 정의하나요?", english: "How do you define success?" },
            { korean: "성공은 제 목표를 달성하는 것입니다.", english: "Success is meeting my goals." },
            { korean: "질문 있으신가요?", english: "Do you have any questions?" },
            { korean: "네, 성장 기회에 대해 알려주세요.", english: "Yes, about growth opportunities." },
            { korean: "팀을 어떻게 이끄나요?", english: "How do you lead a team?" },
            { korean: "명확한 목표를 설정함으로써 이끕니다.", english: "By setting clear objectives." },
            { korean: "문제 해결에 능숙한가요?", english: "Are you good at solving problems?" },
            { korean: "네, 저는 비판적으로 사고합니다.", english: "Yes, I think critically." },
            { korean: "이전 직장을 왜 떠났나요?", english: "Why did you leave your job?" },
            { korean: "더 나은 경력 전망을 찾기 위해 떠났습니다.", english: "To seek better career prospects." },
            { korean: "급여 기대치는 얼마인가요?", english: "What are your salary expectations?" },
            { korean: "공정한 금액을 기대합니다.", english: "I expect a fair amount." },
            { korean: "언제 시작할 수 있나요?", english: "How soon can you start?" },
            { korean: "2주 후에 시작할 수 있습니다.", english: "I can start in two weeks." },
            { korean: "팀워크를 선호하나요?", english: "Do you prefer teamwork?" },
            { korean: "네, 팀 협업을 소중히 여깁니다.", english: "Yes, I value team collaboration." },
            { korean: "비판을 어떻게 다루나요?", english: "How do you handle criticism?" },
            { korean: "저는 건설적으로 받아들입니다.", english: "I take it constructively." },
            { korean: "무엇이 당신에게 동기를 부여하나요?", english: "What motivates you?" },
            { korean: "목표 달성이 저를 동기부여합니다.", english: "Achieving goals motivates me." },
            { korean: "다른 곳에도 지원하고 있나요?", english: "Are you applying elsewhere?" },
            { korean: "네, 다양한 옵션을 탐색 중입니다.", english: "Yes, I am exploring options." }
        ]
    },
    'presentations': {
        name: '프레젠테이션',
        sentences: [
            { korean: "지금 시작해도 될까요?", english: "May I start now?" },
            { korean: "프레젠테이션을 시작해 주세요.", english: "Yes, please begin your presentation." },
            { korean: "오늘 의제는 무엇인가요?", english: "What's today's agenda?" },
            { korean: "분기별 판매 결과를 논의합니다.", english: "Discussing quarterly sales results." },
            { korean: "지금까지 질문 있나요?", english: "Any questions so far?" },
            { korean: "자세히 설명해 주시겠습니까?", english: "Could you please elaborate?" },
            { korean: "제 목소리가 잘 들리나요?", english: "Can you hear me well?" },
            { korean: "네, 모든 것이 명확하게 들립니다.", english: "Yes, everything sounds clear." },
            { korean: "이 그래프는 무엇을 보여주나요?", english: "What does this graph show?" },
            { korean: "우리의 성장 추세를 보여줍니다.", english: "It displays our growth trends." },
            { korean: "피드백을 받을 수 있을까요?", english: "Could I get some feedback?" },
            { korean: "몇 가지 통찰을 제공하겠습니다.", english: "Sure, I'll provide some insights." },
            { korean: "이 데이터가 최신인가요?", english: "Is this data current?" },
            { korean: "네, 지난달까지 업데이트되었습니다.", english: "Yes, it's updated till last month." },
            { korean: "이 점을 요약해 줄 수 있나요?", english: "Who can summarize this point?" },
            { korean: "제가 요약해 보겠습니다.", english: "I can try to summarize." },
            { korean: "잠시 휴식을 취할까요?", english: "Shall we take a short break?" },
            { korean: "이것이 왜 중요한가요?", english: "Why is this important?" },
            { korean: "이것은 우리의 전략에 핵심적입니다.", english: "It's central to our strategy." },
            { korean: "다음 단계는 무엇인가요?", english: "What are our next steps?" },
            { korean: "지금 설명드리겠습니다.", english: "I will outline them now." },
            { korean: "우리의 성과는 어땠나요?", english: "How did we perform?" },
            { korean: "작년보다 나았습니다.", english: "Better than last year." },
            { korean: "다른 관점이 있나요?", english: "Who has another viewpoint?" },
            { korean: "추가하고 싶은 것이 있습니다.", english: "I would like to add something." },
            { korean: "이 부분에 대해 논의할 수 있나요?", english: "Can we discuss this part?" },
            { korean: "그 영역에 집중합시다.", english: "Sure, let's focus on that area." },
            { korean: "결론이 명확한가요?", english: "Is the conclusion clear?" },
            { korean: "네, 완벽히 이해했습니다.", english: "Yes, it makes perfect sense." },
            { korean: "마지막 의견 있나요?", english: "Any final thoughts?" },
            { korean: "이 변경 사항을 실행합시다.", english: "Let's implement these changes." },
            { korean: "이것이 녹화되나요?", english: "Will this be recorded?" },
            { korean: "네, 나중에 녹화본을 보내드리겠습니다.", english: "Yes, we'll send the recording later." }
        ]
    },
    'remote_meeting': {
        name: '원격 회의',
        sentences: [
            { korean: "모두 제 목소리가 들리나요?", english: "Can everyone hear me?" },
            { korean: "네, 잘 들립니다.", english: "Yes, I can hear you." },
            { korean: "제 화면이 보이나요?", english: "Is my screen visible?" },
            { korean: "화면이 잘 보입니다.", english: "The screen is visible." },
            { korean: "다시 말씀해 주시겠습니까?", english: "Can you repeat that?" },
            { korean: "물론, 다시 말씀드리겠습니다.", english: "Sure, I can repeat that." },
            { korean: "지금까지 질문 있으신가요?", english: "Any questions so far?" },
            { korean: "지금까지 질문 없습니다.", english: "No questions so far." },
            { korean: "시작할 준비 되셨나요?", english: "Are we ready to begin?" },
            { korean: "네, 준비되었습니다.", english: "Yes, we are ready." },
            { korean: "제 프레젠테이션이 보이나요?", english: "Can you see my presentation?" },
            { korean: "프레젠테이션이 명확하게 보입니다.", english: "The presentation is clear." },
            { korean: "연결 상태가 안정적인가요?", english: "Is the connection stable?" },
            { korean: "네, 연결 상태가 좋습니다.", english: "Yes, the connection is good." },
            { korean: "마이크를 음소거해 주시겠습니까?", english: "Can you mute your mic?" },
            { korean: "마이크를 음소거하겠습니다.", english: "I will mute my mic." },
            { korean: "오디오에 문제 있나요?", english: "Any issues with audio?" },
            { korean: "오디오에 문제 없습니다.", english: "No issues with audio." },
            { korean: "그 점을 명확히 설명해 주시겠습니까?", english: "Can you clarify that?" },
            { korean: "명확히 설명드리겠습니다.", english: "I can clarify that." },
            { korean: "일정대로 진행되고 있나요?", english: "Are we on schedule?" },
            { korean: "네, 일정대로 진행되고 있습니다.", english: "Yes, we are on schedule." },
            { korean: "지금 시작할 수 있나요?", english: "Can we start now?" },
            { korean: "지금 시작할 수 있습니다.", english: "We can start now." },
            { korean: "모두 통화에 참여했나요?", english: "Is everyone on the call?" },
            { korean: "모두 참여했습니다.", english: "Everyone is on the call." },
            { korean: "업데이트를 제공해 줄 수 있나요?", english: "Can you provide updates?" },
            { korean: "업데이트를 제공하겠습니다.", english: "I will provide updates." },
            { korean: "지금까지 피드백 있나요?", english: "Any feedback so far?" },
            { korean: "지금까지 피드백 없습니다.", english: "No feedback so far." },
            { korean: "세부사항을 이메일로 보내줄 수 있나요?", english: "Can you email the details?" },
            { korean: "세부사항을 이메일로 보내겠습니다.", english: "I will email the details." },
            { korean: "비디오가 잘 작동하나요?", english: "Is the video working?" },
            { korean: "비디오가 잘 작동합니다.", english: "The video is working fine." },
            { korean: "내일에 대해 논의할 수 있나요?", english: "Can we discuss tomorrow?" },
            { korean: "내일에 대해 논의할 수 있습니다.", english: "We can discuss tomorrow." }
        ]
    },
    'time_and_attendance': {
        name: '근태',
        sentences: [
            { korean: "몇 시에 도착했나요?", english: "What time did you arrive?" },
            { korean: "오전 8시에 들어왔습니다.", english: "I came in at 8:00 a.m." },
            { korean: "오늘 모두 출근 기록을 했나요?", english: "Did everyone sign in today?" },
            { korean: "네, 모두 출근표에 서명했습니다.", english: "Yes, everyone signed the sheet." },
            { korean: "출근 기록부를 확인해 줄 수 있나요?", english: "Can you check the log book?" },
            { korean: "지금 확인하겠습니다.", english: "Sure, I'll check it now." },
            { korean: "누가 출근하지 않았나요?", english: "Who is missing from work?" },
            { korean: "존이 오늘 병가로 전화했습니다.", english: "John called in sick today." },
            { korean: "근무 시간을 어떻게 기록하나요?", english: "How do I log my hours?" },
            { korean: "전자 시간 시스템을 사용하세요.", english: "Use the electronic time system." },
            { korean: "출근표가 업데이트되었나요?", english: "Is the attendance sheet updated?" },
            { korean: "몇 시간마다 업데이트됩니다.", english: "It's updated every few hours." },
            { korean: "회의 시간이 변경되었나요?", english: "Was the meeting time changed?" },
            { korean: "네, 이제 오후 3시입니다.", english: "Yes, it's now at 3:00 p.m." },
            { korean: "초과 근무 시간을 누가 기록하나요?", english: "Who logs the overtime hours?" },
            { korean: "매주 금요일 제가 기록합니다.", english: "I do that every Friday." },
            { korean: "오늘 일찍 퇴근할 수 있나요?", english: "Can we leave early today?" },
            { korean: "업무가 완료되었다면 가능합니다.", english: "Only if your work is done." },
            { korean: "다시 출근 기록을 해야 하나요?", english: "Should I clock in again?" },
            { korean: "아니요, 아침에 한 번만 하면 됩니다.", english: "No, just once in the morning." },
            { korean: "지각에 대한 규정은 무엇인가요?", english: "What's the protocol for lateness?" },
            { korean: "인사부와 상사에게 알려야 합니다.", english: "Inform HR and your supervisor." },
            { korean: "타이머는 어떻게 사용하나요?", english: "How do I use the timer?" },
            { korean: "도착 시 시작 버튼을 누르세요.", english: "Press start when you arrive." },
            { korean: "이번 주 일정이 준비되었나요?", english: "Is this week's schedule ready?" },
            { korean: "네, 게시판에 있습니다.", english: "Yes, it's on the notice board." },
            { korean: "휴식 시간도 기록해야 하나요?", english: "Do we log breaks as well?" },
            { korean: "네, 모든 휴식 시간을 기록하세요.", english: "Yes, log all breaks taken." },
            { korean: "왜 제가 결근으로 표시되었나요?", english: "Why was I marked absent?" },
            { korean: "어제 출근 기록을 하지 않았습니다.", english: "You didn't sign in yesterday." },
            { korean: "오늘 타임시트를 제출해야 하나요?", english: "Are time sheets due today?" },
            { korean: "네, 오후 5시까지 제출하세요.", english: "Yes, submit them by 5:00 p.m." },
            { korean: "근무 시간을 변경할 수 있나요?", english: "Can I switch my shift?" },
            { korean: "먼저 관리자와 확인하세요.", english: "Check with management first." }
        ]
    },
    'workplace_conversation': {
        name: '직장 대화',
        sentences: [
            { korean: "이 프로젝트에 대해 논의할 수 있을까요?", english: "Can we discuss this project?" },
            { korean: "함께 검토합시다.", english: "Yes, let's review it together." },
            { korean: "도움이 필요하신가요?", english: "Do you need any help?" },
            { korean: "묻는 것에 감사하지만 괜찮습니다.", english: "No, thank you for asking." },
            { korean: "회의는 언제 예정되어 있나요?", english: "When is the meeting scheduled?" },
            { korean: "내일 아침으로 예정되어 있습니다.", english: "It's set for tomorrow morning." },
            { korean: "이것을 더 자세히 설명해 주시겠습니까?", english: "Could you explain this further?" },
            { korean: "물론, 명확히 설명드리겠습니다.", english: "Sure, I can clarify it." },
            { korean: "오늘 일찍 퇴근해도 되나요?", english: "May I leave early today?" },
            { korean: "네, 괜찮습니다.", english: "Yes, that should be fine." },
            { korean: "이 파일들을 업데이트해 줄 수 있나요?", english: "Can you update these files?" },
            { korean: "정오까지 처리하겠습니다.", english: "I'll do it by noon." },
            { korean: "이것의 마감일은 언제인가요?", english: "What's the deadline for this?" },
            { korean: "마감일은 다음 금요일입니다.", english: "The deadline is next Friday." },
            { korean: "이 업무를 누가 이끌고 있나요?", english: "Who is leading this task?" },
            { korean: "마이클이 책임자입니다.", english: "Michael will be in charge." },
            { korean: "클라이언트에게 이메일을 보내야 하나요?", english: "Should I email the client?" },
            { korean: "네, 자세히 작성해 주세요.", english: "Yes, please ensure it's detailed." },
            { korean: "회의실이 비어 있나요?", english: "Is the conference room free?" },
            { korean: "오후 3시에 이용 가능합니다.", english: "It's available at 3:00." },
            { korean: "이것을 어떻게 작동시키나요?", english: "How do I operate this?" },
            { korean: "방법을 보여드리겠습니다.", english: "Let me show you how." },
            { korean: "회의를 연기할 수 있나요?", english: "Can we postpone our meeting?" },
            { korean: "그게 저에게 더 편합니다.", english: "That works better for me." },
            { korean: "보고서가 아직 준비되었나요?", english: "Are the reports ready yet?" },
            { korean: "곧 준비될 것입니다.", english: "They will be ready soon." },
            { korean: "휴식 시간은 언제인가요?", english: "What time is the break?" },
            { korean: "휴식은 오후 12시에 시작됩니다.", english: "Break starts at 12:00 p.m." },
            { korean: "공급업체에 전화해 줄 수 있나요?", english: "Could you call the supplier?" },
            { korean: "오늘 처리하겠습니다.", english: "I will handle it today." },
            { korean: "아이디어를 제안해도 될까요?", english: "May I suggest an idea?" },
            { korean: "당연히, 아이디어는 언제나 환영입니다.", english: "Absolutely, your ideas are welcome." },
            { korean: "이 데이터가 정확한가요?", english: "Is this data correct?" },
            { korean: "네, 모두 이중으로 확인했습니다.", english: "Yes, everything was double-checked." }
        ]
    },
    'workplace_small_talk': {
        name: '직장 스몰토크',
        sentences: [
            { korean: "오늘 날씨가 좋지 않나요?", english: "Nice weather today, isn't it?" },
            { korean: "네, 정말 좋습니다.", english: "Yes, it's really nice." },
            { korean: "어느 층으로 가시나요?", english: "Which floor are you going?" },
            { korean: "5층으로 갑니다.", english: "I'm going to the fifth." },
            { korean: "여기서 일하시나요?", english: "Do you work here?" },
            { korean: "네, 저도 여기서 일합니다.", english: "Yes, I also work here." },
            { korean: "얼마나 오래 근무하셨나요?", english: "How long have you worked?" },
            { korean: "5년 됐습니다.", english: "Five years now." },
            { korean: "이달에 막 시작했어요.", english: "Just started this month." },
            { korean: "일이 마음에 드시나요?", english: "Do you enjoy it?" },
            { korean: "네, 지금까지 좋습니다.", english: "Yes, it's good so far." },
            { korean: "무슨 일을 하시나요?", english: "What do you do?" },
            { korean: "저는 마케팅 어시스턴트입니다.", english: "I'm a marketing assistant." },
            { korean: "흥미롭네요!", english: "Oh, that's interesting." },
            { korean: "당신은 어떤 일을 하시나요?", english: "What about you?" },
            { korean: "저는 영업 부서에 있습니다.", english: "I'm in sales department." },
            { korean: "영업이 잘 되나요?", english: "How's the sales going?" },
            { korean: "매우 바쁘지만 보람 있습니다.", english: "Very busy but fulfilling." },
            { korean: "좋은 소식이네요!", english: "That's good to hear." },
            { korean: "이 근처 출신이신가요?", english: "Are you from around here?" },
            { korean: "아니요, 최근에 이사 왔습니다.", english: "No, I moved recently." },
            { korean: "어느 도시에서 오셨나요?", english: "From which city?" },
            { korean: "샌프란시스코에서 왔습니다.", english: "From San Francisco." },
            { korean: "그곳이 그립나요?", english: "Do you miss it?" },
            { korean: "가끔이지만 여기도 좋아합니다.", english: "Sometimes, but I like here." },
            { korean: "알게 되어 반갑습니다.", english: "That's nice to know." },
            { korean: "주말 계획이 있으신가요?", english: "Plans for the weekend?" },
            { korean: "가족을 방문할 예정입니다.", english: "I'm visiting family." },
            { korean: "재미있겠네요!", english: "That sounds fun." },
            { korean: "당신은 어떤 계획이 있나요?", english: "What about you?" },
            { korean: "별다른 계획 없이 그냥 쉴 예정입니다.", english: "Not much, just relaxing." },
            { korean: "휴식이 중요하죠.", english: "It's important to rest." },
            { korean: "맞아요, 정말 그렇습니다.", english: "Yes, indeed it is." },
            { korean: "제 층이에요.", english: "Here's my floor." },
            { korean: "대화 즐거웠습니다.", english: "Nice talking with you." }
        ]
    }
};

// 카테고리 이름 매핑
const categoryNames = {
    'ask_questions_in_conferences': '컨퍼런스 질문하기',
    'business_travel': '출장',
    'conference_ice_breakers': '컨퍼런스 아이스브레이커',
    'conferences': '컨퍼런스',
    'external_meetings': '외부 회의',
    'internal_mail': '내부 메일',
    'internal_meetings': '내부 회의',
    'internal_supplies': '내부 용품',
    'introducing_company': '회사 소개',
    'job_interviews': '면접',
    'presentations': '프레젠테이션',
    'remote_meeting': '원격 회의',
    'time_and_attendance': '근태',
    'workplace_conversation': '직장 대화',
    'workplace_small_talk': '직장 스몰토크'
};